### ISSUE TITLE
Dark mode Docs issue, iOS, install-module page

### ISSUE THREAD

**Issue by Seanmclem** [OpenNative/open-native#14]
When the install-module page renders, especially if you have dark mode on, the text is dark, and so is the background of the code sample. This specifically happened to me with iOS. Every browser. Because they are all Safari. See below.
![image](https://user-images.githubusercontent.com/6831540/215597733-2bd0d1cc-c6a1-4d15-8b68-98c4f606b8a8.png)

**Comment by ammarahm-ed** [comment]
Thanks for reporting. I will fix this asap.

**Comment by ammarahm-ed** [comment]
Hey, this has been fixed.
